# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Krithic Kumar
tagline:          'A Jekyll theme'
description:      'My musings on computer science and technology'
baseurl:          /

author:
  name:           'Krithic Kumar'
  url:            https://jedi.github.io

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-gist
  - jekyll-paginate

github:           https://github.com/jedi2610
